import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>poke-next-aip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.headerBar}>
          <h1 className={styles.title}>
            Welcome to <a href="https://www.pokemon.com/us/">PokeNext</a>
          </h1>
          <div className={styles.headerMenu}>
            <Link href="/pokemon" cllinkssName={styles.headRoutes}>
              Pokémon
            </Link>
            <Link href="/pokessr" className={styles.headRoutes}>
              Poke SSR
            </Link>
            <Link href="/pokessg" className={styles.headRoutes}>
              Poke SSG
            </Link>
            <Link href="/pokeisr" className={styles.headRoutes}>
              Poke ISR
            </Link>
          </div>
        </header>
        Powered by{" your worst nightmare"}
      </main>
    </div>
  );
}
