import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>poke-next-aip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <header className={styles.headerBar}>
          <h1 className={styles.title}>
            Welcome to <a href="https://www.pokemon.com/us/">PokeNext</a>
          </h1>
          <div className={styles.headerMenu}>
            <h2 className={styles.headRoutes}>Pokémon</h2>
            <h2 className={styles.headRoutes}>Poke SSR</h2>
            <h2 className={styles.headRoutes}>Poke SSG</h2>
            <h2 className={styles.headRoutes}>Poke ISR</h2>
          </div>
        </header>
        Powered by{" your worst nightmare"}
      </main>
    </div>
  );
}
