import Head from "next/head";
import Image from "next/image";

export default function Pokemon() {
  return (
    <div>
      <Head>
        <title>poke-next-aip</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <header>
          <h1>
            Welcome to <a href="https://www.pokemon.com/us/">Pokeoooooo</a>
          </h1>
        </header>
        Powered by{" your worst nightmare"}
      </main>
    </div>
  );
}
